sudo: required
language: cpp
dist: trusty

git:
  depth: 5

os:
  - linux

compiler:
  - g++
  - clang++

arch:
  packages:
    - cmake
    - gcc
    - clang
    - boost
    - protobuf

  script:
    - git submodule update --init
    - mkdir build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug
    - make -j4

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

# branches:
#   only:
#     - master

notifications:
  recipients: []
  email:
    on_success: change
    on_failure: always